version: '3.8'

services:
  app:
    image: grupodapaz-web:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      # Configurações de Email (Mailpit)
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=noreply@grupodapazbr.com.br
    volumes:
      - ./attached_assets:/app/attached_assets
    restart: unless-stopped
    networks:
      - app-network

  # Mailpit - Sistema de emails para desenvolvimento/testes
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    restart: unless-stopped
    networks:
      - app-network

  # Interface web Roundcube para funcionários
  roundcube:
    image: roundcube/roundcubemail:latest
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailpit
      - ROUNDCUBEMAIL_DEFAULT_PORT=1025
      - ROUNDCUBEMAIL_SMTP_SERVER=mailpit
      - ROUNDCUBEMAIL_SMTP_PORT=1025
    volumes:
      - roundcube_data:/var/www/html
    depends_on:
      - mailpit
    restart: unless-stopped
    networks:
      - app-network

  # Interface de administração
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - app-network

  # Nginx como proxy reverso para domínios
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  roundcube_data:

networks:
  app-network:
    driver: bridge