#!/bin/bash

echo "=========================================="
echo "  POSTE.IO - SERVIDOR DE EMAIL CORPORATIVO"
echo "  Grupo da Paz - Configuração Completa"
echo "=========================================="
echo ""

echo "🚀 POSTE.IO - A MELHOR SOLUÇÃO DE EMAIL CORPORATIVO!"
echo ""
echo "📧 FUNCIONALIDADES INCLUÍDAS:"
echo "✅ Interface web moderna e intuitiva"
echo "✅ Anti-spam e anti-vírus integrados"
echo "✅ Backup automático"
echo "✅ SSL/TLS automático"
echo "✅ Webmail completo (Roundcube)"
echo "✅ Painel administrativo avançado"
echo "✅ Quotas por usuário"
echo "✅ Aliases e redirecionamentos"
echo "✅ API REST completa"
echo "✅ Monitoramento em tempo real"
echo ""

echo "🌐 CONFIGURAÇÃO DNS NECESSÁRIA:"
echo "Adicione estes registros DNS no seu provedor:"
echo ""
echo "Tipo: A     Nome: mail.grupodapazbr.com.br    Valor: 104.131.19.89"
echo "Tipo: MX    Nome: grupodapazbr.com.br         Valor: mail.grupodapazbr.com.br (Prioridade: 10)"
echo "Tipo: TXT   Nome: grupodapazbr.com.br         Valor: v=spf1 mx ~all"
echo "Tipo: TXT   Nome: _dmarc.grupodapazbr.com.br  Valor: v=DMARC1; p=quarantine; rua=mailto:admin@grupodapazbr.com.br"
echo ""

echo "📧 ACESSOS APÓS CONFIGURAÇÃO:"
echo ""
echo "1. 🌐 Site Principal:"
echo "   https://grupodapazbr.com.br"
echo ""
echo "2. ⚙️ Painel Admin Poste.io:"
echo "   https://grupodapazbr.com.br/admin"
echo "   (Primeiro acesso: admin@grupodapazbr.com.br)"
echo ""
echo "3. 📨 Webmail:"
echo "   https://grupodapazbr.com.br/webmail"
echo ""
echo "4. 📬 Acesso Direto Poste.io:"
echo "   http://104.131.19.89:8080"
echo ""

echo "🔧 CONFIGURAÇÃO DE CLIENTES DE EMAIL:"
echo "Servidor SMTP: mail.grupodapazbr.com.br:587 (TLS)"
echo "Servidor IMAP: mail.grupodapazbr.com.br:993 (SSL)"
echo "Servidor POP3: mail.grupodapazbr.com.br:995 (SSL)"
echo ""

echo "🚀 PARA INICIAR O SERVIDOR:"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""

echo "📋 PRIMEIROS PASSOS:"
echo "1. Configure os registros DNS"
echo "2. Acesse http://104.131.19.89:8080"
echo "3. Configure o domínio: grupodapazbr.com.br"
echo "4. Crie usuários através do painel admin"
echo "5. Configure SSL automático"
echo ""

echo "✨ VANTAGENS DO POSTE.IO:"
echo "• Interface moderna e responsiva"
echo "• Configuração automática de SSL"
echo "• Backup automático diário"
echo "• Monitoramento em tempo real"
echo "• API REST para integrações"
echo "• Suporte a múltiplos domínios"
echo "• Interface similar ao G Suite"
echo ""

echo "=========================================="
echo "✅ Configuração Poste.io concluída!"
echo "🎉 PRONTO PARA USO CORPORATIVO!"
echo "=========================================="
