name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t grupodapaz-web:latest .

    - name: Save Docker image
      run: |
        docker save grupodapaz-web:latest | gzip > grupodapaz-web.tar.gz

    - name: Transfer image to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        port: 22
        source: "grupodapaz-web.tar.gz"
        target: "/tmp/"

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        port: 22
        script: |
          # Load the Docker image
          docker load < /tmp/grupodapaz-web.tar.gz
          
          # Stop existing container
          docker-compose -f /opt/grupodapaz-web/docker-compose.prod.yml down || true
          
          # Start new container
          cd /opt/grupodapaz-web
          docker-compose -f docker-compose.prod.yml up -d
          
          # Clean up
          rm /tmp/grupodapaz-web.tar.gz
          docker image prune -f
          
          # Show status
          docker ps
